import { Outfit } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import ThemeSync from "@/Components/ThemeSync";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const outfit = Outfit({subsets: ["latin"], weight: ["400","500","600","700"]});

export const metadata = {
  title: "Blog App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${outfit.className} bg-white dark:bg-amber-50 text-black dark:text-gray-900 transition-colors duration-300`}>
          <Providers>
            <ThemeSync />
            <ToastContainer theme="dark" position="top-right" autoClose={2500}/>
            {children}
          </Providers>
      </body>
    </html>
  );
}
